
services:
  redis:
    image: redis:alpine  # Версия образа для redis
    container_name: redis_cache #Название контейнера в Docker

    ports:
      - "6379:6379" #Проброс портов из контейнера

    restart: always #Опция перезапуска

    healthcheck: #Проверка работы контейнера
      test: ["CMD","redis-cli",ping] #Команда проверки
      interval: 30s #Интервал проверки
      timeout: 5s   #Ожидание ответа
      retries: 5 #Количество попыток получить ответ от контейнера


    volumes: #Создание тома data в redis
      - redis_data:/redis

  jaeger:
    image: jaegertracing/jaeger:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

    restart: always
    environment:
      - DEBUG=true
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"

    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prprometheus
      
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.retention.time=24h'  
    
    restart: always
   
    networks:
      - monitoring

volumes:
  redis_data:
    driver: local
  prometheus_data:
    driver: local
    
networks:
  monitoring:
    driver: bridge

 