global:
  scrape_interval: 15s      # Интервал сбора метрик
  scrape_timeout: 10s       # Время ожидания ответа от сервера
  evaluation_interval: 15s  # Интерва проверки праил аллертов

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Мониторинг Prometheus

  - job_name: 'gRPC-services'
    static_configs:
      - targets: 
        - 'host.docker.internal:9464' #Порты для работы сервисов
        - 'host.docker.internal:9465'
    metrics_path: /metrics