// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: Protobuf/SpotService.proto

package spotAPI

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User_Roles int32

const (
	User_Roles_ROLE_UNSPECIFIED User_Roles = 0
	User_Roles_ROLE_USER        User_Roles = 1
	User_Roles_ROLE_ADMIN       User_Roles = 2
)

// Enum value maps for User_Roles.
var (
	User_Roles_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_USER",
		2: "ROLE_ADMIN",
	}
	User_Roles_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_USER":        1,
		"ROLE_ADMIN":       2,
	}
)

func (x User_Roles) Enum() *User_Roles {
	p := new(User_Roles)
	*p = x
	return p
}

func (x User_Roles) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (User_Roles) Descriptor() protoreflect.EnumDescriptor {
	return file_Protobuf_SpotService_proto_enumTypes[0].Descriptor()
}

func (User_Roles) Type() protoreflect.EnumType {
	return &file_Protobuf_SpotService_proto_enumTypes[0]
}

func (x User_Roles) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use User_Roles.Descriptor instead.
func (User_Roles) EnumDescriptor() ([]byte, []int) {
	return file_Protobuf_SpotService_proto_rawDescGZIP(), []int{0}
}

// Запрос для ViewMarket
type ViewReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserRoles     User_Roles             `protobuf:"varint,1,opt,name=user_roles,json=userRoles,proto3,enum=spotAPI.User_Roles" json:"user_roles,omitempty"` //Поле для юзера
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewReq) Reset() {
	*x = ViewReq{}
	mi := &file_Protobuf_SpotService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewReq) ProtoMessage() {}

func (x *ViewReq) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_SpotService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewReq.ProtoReflect.Descriptor instead.
func (*ViewReq) Descriptor() ([]byte, []int) {
	return file_Protobuf_SpotService_proto_rawDescGZIP(), []int{0}
}

func (x *ViewReq) GetUserRoles() User_Roles {
	if x != nil {
		return x.UserRoles
	}
	return User_Roles_ROLE_UNSPECIFIED
}

// Ответ для ViewMarket
type ViewResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnableMarkets []int64                `protobuf:"varint,1,rep,packed,name=enable_markets,json=enableMarkets,proto3" json:"enable_markets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewResp) Reset() {
	*x = ViewResp{}
	mi := &file_Protobuf_SpotService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewResp) ProtoMessage() {}

func (x *ViewResp) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_SpotService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewResp.ProtoReflect.Descriptor instead.
func (*ViewResp) Descriptor() ([]byte, []int) {
	return file_Protobuf_SpotService_proto_rawDescGZIP(), []int{1}
}

func (x *ViewResp) GetEnableMarkets() []int64 {
	if x != nil {
		return x.EnableMarkets
	}
	return nil
}

var File_Protobuf_SpotService_proto protoreflect.FileDescriptor

const file_Protobuf_SpotService_proto_rawDesc = "" +
	"\n" +
	"\x1aProtobuf/SpotService.proto\x12\aspotAPI\"=\n" +
	"\aViewReq\x122\n" +
	"\n" +
	"user_roles\x18\x01 \x01(\x0e2\x13.spotAPI.User_RolesR\tuserRoles\"1\n" +
	"\bViewResp\x12%\n" +
	"\x0eenable_markets\x18\x01 \x03(\x03R\renableMarkets*A\n" +
	"\n" +
	"User_Roles\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tROLE_USER\x10\x01\x12\x0e\n" +
	"\n" +
	"ROLE_ADMIN\x10\x022J\n" +
	"\x15SpotInstrumentService\x121\n" +
	"\n" +
	"ViewMarket\x12\x10.spotAPI.ViewReq\x1a\x11.spotAPI.ViewRespB\x19Z\x17./Protobuf/spot;spotAPIb\x06proto3"

var (
	file_Protobuf_SpotService_proto_rawDescOnce sync.Once
	file_Protobuf_SpotService_proto_rawDescData []byte
)

func file_Protobuf_SpotService_proto_rawDescGZIP() []byte {
	file_Protobuf_SpotService_proto_rawDescOnce.Do(func() {
		file_Protobuf_SpotService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Protobuf_SpotService_proto_rawDesc), len(file_Protobuf_SpotService_proto_rawDesc)))
	})
	return file_Protobuf_SpotService_proto_rawDescData
}

var file_Protobuf_SpotService_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Protobuf_SpotService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Protobuf_SpotService_proto_goTypes = []any{
	(User_Roles)(0),  // 0: spotAPI.User_Roles
	(*ViewReq)(nil),  // 1: spotAPI.ViewReq
	(*ViewResp)(nil), // 2: spotAPI.ViewResp
}
var file_Protobuf_SpotService_proto_depIdxs = []int32{
	0, // 0: spotAPI.ViewReq.user_roles:type_name -> spotAPI.User_Roles
	1, // 1: spotAPI.SpotInstrumentService.ViewMarket:input_type -> spotAPI.ViewReq
	2, // 2: spotAPI.SpotInstrumentService.ViewMarket:output_type -> spotAPI.ViewResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Protobuf_SpotService_proto_init() }
func file_Protobuf_SpotService_proto_init() {
	if File_Protobuf_SpotService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Protobuf_SpotService_proto_rawDesc), len(file_Protobuf_SpotService_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Protobuf_SpotService_proto_goTypes,
		DependencyIndexes: file_Protobuf_SpotService_proto_depIdxs,
		EnumInfos:         file_Protobuf_SpotService_proto_enumTypes,
		MessageInfos:      file_Protobuf_SpotService_proto_msgTypes,
	}.Build()
	File_Protobuf_SpotService_proto = out.File
	file_Protobuf_SpotService_proto_goTypes = nil
	file_Protobuf_SpotService_proto_depIdxs = nil
}
