server:
  port: 
  host: 
  network: "tcp"

postgres:
  host: 
  port: 
  user: 
  password: 
  name: 
  sslmode: "disable"
  chan_size: 10

breakersetting:
  name: "OrderService"
  max_request: 5
  interval: 60
  timeout: 10
  max_fail_request: 10

jaeger:
  host: 
  port: 
